### ISSUE TITLE
Accounts Detail View: API request to /v1/accounts?budget={budgetId}

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#1018]
**Describe the bug**
When loading the account detail view, there is a request to the backend for `/v1/accounts?budget={budgetId}`

**To Reproduce**

1. Open the account detail view for any account and inspect the network requests

**Expected behavior**
This API call **looks** not necessary to me. We should find out why we're making it and eliminate it, if possible.

**Comment by malfynnction** [comment]
@morremeyer I can't reproduce this? The only requests I see are to `/v1/accounts/$ID` and to `/v1/transactions?account=$ID` which are both necessary 🤔

**Comment by morremeyer** [comment]
Traced it back to https://github.com/envelope-zero/frontend/blob/2db34aed3739e6a46894f025f2347f360a8e2e3d/src/App.tsx#L80, which is loaded on **every** page even when we don't need the accounts.

**Comment by malfynnction** [comment]
I just checked again, the account detail view actually needs to load all accounts, in order to choose the correct styling for the latest transactions: it needs to check if the other accounts are internal in order to distinguish income, outflow, and transfers.

At this point, I am not sure if the "Latest Transactions" list on that page is actually necessary/useful. Maybe it should just be a link to the filtered transaction list (like the "Show All" button currently does). What do you think?

**Comment by morremeyer** [comment]
Yeah, I think removing the transaction list in the account detail view makes sense.

With that, we can also remove the line I linked and only load the accounts in the transaction list (for styling the amount) and forms (for auto-completion), I think. Or am I missing something?
